// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mobil1.Data;

#nullable disable

namespace Mobil1.Migrations
{
    [DbContext(typeof(Mobil1DbContext))]
    partial class Mobil1DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mobil1.Models.Fatura", b =>
                {
                    b.Property<int>("Fatura_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Fatura_Id"));

                    b.Property<int>("FaturaBilgi_Id")
                        .HasColumnType("int");

                    b.Property<int>("Fatura_BilgiFaturaBilgi_Id")
                        .HasColumnType("int");

                    b.Property<string>("Fatura_Numarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Onay_Durumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sirket_Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Toplam_Tutar")
                        .HasColumnType("real");

                    b.HasKey("Fatura_Id");

                    b.HasIndex("Fatura_BilgiFaturaBilgi_Id");

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("Mobil1.Models.Fatura_Bilgi", b =>
                {
                    b.Property<int>("FaturaBilgi_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaturaBilgi_Id"));

                    b.Property<string>("Fatura_Tipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KDV_Orani")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SirketAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SirketTelefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FaturaBilgi_Id");

                    b.ToTable("FaturaBilgileri");
                });

            modelBuilder.Entity("Mobil1.Models.Fatura", b =>
                {
                    b.HasOne("Mobil1.Models.Fatura_Bilgi", "Fatura_Bilgi")
                        .WithMany()
                        .HasForeignKey("Fatura_BilgiFaturaBilgi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fatura_Bilgi");
                });
#pragma warning restore 612, 618
        }
    }
}
